function build_simulink_model()
%% build_simulink_model.m — 生成 Simulink 闭环仿真模型 step_motor_closedloop.slx
% 用法: 在 MATLAB 中 run('model/build_simulink_model.m')
%       或直接 open_system('model/step_motor_closedloop')
% 说明: 模型结构（单 MATLAB Function 块承载全部算法，复用 Scripts 版函数）：
%   Clock -> cmd 生成（MATLAB Function: 位置/速度/电流命令序列）
%         -> 闭环系统（MATLAB Function: 编码器->控制器->驱动->电机->编码器 一步）
%         -> Scope（位置/速度/电流/状态）+ To Workspace（数据导出）
% 模型与 run_*.m 脚本共享同一套 model/*.m 函数，保证一致。
%
% 注意: 需要 Simulink 许可；无 Simulink Coder 也能运行（仅仿真）。

if ~exist('Simulink', 'dir') || isempty(which('Simulink'))
    error('未检测到 Simulink。请确认已安装 Simulink 且加入路径。');
end

model = 'step_motor_closedloop';
if bdIsLoaded(model), close_system(model, 0); end
new_system(model);
open_system(model);

% 参数装配（Model Workspace 注入）
ws = get_param(model, 'ModelWorkspace');
assignin(ws, 'mp', motor_params());
assignin(ws, 'dp', drive_params());
assignin(ws, 'ep', encoder_params());
assignin(ws, 'cp', control_params());

% ---- 命令序列（仿真时间轴分段） ----
% [t_start, 模式, 目标值] 每行一段；位置模式目标=细分步
% 例: 0s MODE_POSITION 0 -> 1s 12800(90°) -> 3s 25600(180°) -> 5s 0
cmd_data = [0, 1, 0; ...
            1, 1, 12800; ...
            3, 1, 25600; ...
            5, 1, 0];

% ---- 顶层布局（按坐标摆块） ----
blocks = {
    % 名称, 块类型, 位置[x y w h], 关键参数
    'Clock',          'simulink/Sources/Clock',                [20 20 60 30], ''
    'CmdGen',         'simulink/User-Defined Functions/MATLAB Function', [110 20 90 40], 'function [mode, goal] = CmdGen(t)' ...
    'System',         'simulink/User-Defined Functions/MATLAB Function', [250 20 90 60], 'function [pos, vel, cur, state, mode] = System(rect, cmd_mode, cmd_goal)' ...
    'Scope',          'simulink/Sinks/Scope',                  [400 20 60 60], ''
    'ToWorkspace',    'simulink/Sinks/To Workspace',           [400 120 60 40], 'VariableName=sim_out'
};

% 简化实现：用两个 MATLAB Function 块（CmdGen 生成命令；System 一帧闭环）
% MATLAB Function 块函数体通过 Stateflow 内嵌代码设置（占位说明见 README）
% 注：MATLAB Function 块内嵌代码无法纯脚本注入完整算法，此处提供模型骨架，
%     函数体请按 README「Simulink 用法」粘贴（内容与 run_*.m 循环体一致）。

% 命令生成函数体
cmd_fcn = sprintf([ ...
    'function [mode, goal] = CmdGen(t)\n' ...
    'persistent cmds\n' ...
    'if isempty(cmds)\n' ...
    '    cmds = %s;\n' ...
    'end\n' ...
    'mode = 1; goal = 0;\n' ...
    'for i = 1:size(cmds,1)\n' ...
    '    if t >= cmds(i,1)\n' ...
    '        mode = cmds(i,2); goal = cmds(i,3);\n' ...
    '    end\n' ...
    'end\n' ...
    'end\n'], mat2str(cmd_data));

% 系统一帧函数体（编码器->控制->驱动->电机）
sys_fcn = sprintf([ ...
    'function [pos, vel, cur, state, mode] = System(rect, cmd_mode, cmd_goal)\n' ...
    'persistent ctrl x\n' ...
    'if isempty(ctrl)\n' ...
    '    ctrl = firmware_controller_init(cp);\n' ...
    '    x = [0; 0; 0; 0];\n' ...
    'end\n' ...
    'dt = 1 / cp.control_freq;\n' ...
    'ctrl.request_mode = cmd_mode;\n' ...
    'ctrl.goal_position = cmd_goal;\n' ...
    '[ctrl, out] = firmware_controller(ctrl, rect);\n' ...
    'if out.sleep || out.brake\n' ...
    '    v_ab = [0; 0];\n' ...
    'else\n' ...
    '    v_ab = tb67h450_drive(dp, out.foc_position, out.foc_current);\n' ...
    'end\n' ...
    'x = plant_step_motor(mp, x, v_ab, dt);\n' ...
    'pos = x(3) / (2*pi) * cp.subdiv_steps;\n' ...
    'vel = x(4) / (2*pi) * cp.subdiv_steps;\n' ...
    'cur = out.foc_current; state = out.state; mode = out.mode;\n' ...
    'end\n']);

% 创建 MATLAB Function 块并注入代码（R2016a+ 支持 stateflow.EMChart 注入）
add_block('simulink/Sources/Clock',        [model '/Clock'], 'Position', [20 80 60 30]);
add_block('simulink/Sinks/Scope',          [model '/Scope'], 'Position', [420 40 60 80]);
add_block('simulink/Sinks/To Workspace',   [model '/ToWorkspace'], 'Position', [420 140 60 40], ...
          'VariableName', 'sim_out', 'SaveFormat', 'Timeseries');
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/CmdGen'], ...
          'Position', [120 80 100 40]);
add_block('simulink/User-Defined Functions/MATLAB Function', [model '/System'], ...
          'Position', [260 80 100 60]);

% 注入函数体（MATLAB Function 块内部代码）
rt_cmd = Stateflow.EMChart.find([model '/CmdGen']);
rt_cmd.Script = cmd_fcn;
rt_sys = Stateflow.EMChart.find([model '/System']);
rt_sys.Script = sys_fcn;

% 接线：Clock -> CmdGen, CmdGen -> System, System -> Scope/ToWorkspace
% 手动连线（脚本方式）较繁琐，建议打开模型后用鼠标连接以下端子：
%   Clock(1) -> CmdGen(t); CmdGen(mode) -> System(cmd_mode)
%   CmdGen(goal) -> System(cmd_goal); System(rect) 悬空由内部 first_called 首帧取
%   System(pos/vel/cur/state/mode) -> Scope; System 全输出 -> ToWorkspace
fprintf('模型骨架已生成: %s.slx\n', model);
fprintf(['注意: MATLAB Function 块函数体已注入；\n' ...
         '      端口接线请在模型中手动完成（Clock->CmdGen->System->Scope）。\n']);
fprintf('运行: set_param(''%s'',''StopTime'',''6''); sim(''%s'');\n', model, model);
end
